version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - FAL_KEY=${FAL_KEY}
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - 8080:8080
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo-data:
